### ISSUE TITLE
Training and test data

### ISSUE THREAD

**Issue by cemevin** [sammanthp007/Stock-Price-Prediction-Using-KNN-Algorithm#1]
Hi,

I checked your code and noticed that you divide training and test data randomly, based on a split ratio. However in the case of stock markets, I dont think you can do that, since this data is time sensitive. Future prices may imply past prices. When I edited your code to reflect this change (divide the first 70% of the data as training set and last 30% as test set), the accuracy drops down to 50%, unfortunately. I wish it didnt :)

Best,
Cem

**Comment by AbuDev002** [comment]
Hi 
please assist me am having this error when i tried to run the code on my pc. Thanks
>>> 
====== RESTART: C:\pythonprojects\stockmarketprediction\knnAlgorithm.py ======
making a network request
done making network call
Traceback (most recent call last):
  File "C:\pythonprojects\stockmarketprediction\knnAlgorithm.py", line 211, in <module>
    main()
  File "C:\pythonprojects\stockmarketprediction\knnAlgorithm.py", line 204, in main
    predictFor(5, 'amtd.csv', 'AMTD', startdate, enddate, 1, split)
  File "C:\pythonprojects\stockmarketprediction\knnAlgorithm.py", line 141, in predictFor
    getData(filename, stockname, startdate, enddate)
  File "C:\pythonprojects\stockmarketprediction\knnAlgorithm.py", line 120, in getData
    stockwriter.writerow([new_format_date] + [stck_dates[i]["Open"]] +  [stck_dates[i]["High"]] + [stck_dates[i]["Low"]]  +  [stck_dates[i]["Adj Close"]] + [change(stck_dates[i]["Adj Close"], prev_closing)])
TypeError: a bytes-like object is required, not 'str'

**Comment by alanpicard** [comment]
Hi,

I'm having the same problem than AbuDev002.

Thanks

Alan

**Comment by HarshalGoyal** [comment]
> Hi,
> 
> I checked your code and noticed that you divide training and test data randomly, based on a split ratio. However in the case of stock markets, I dont think you can do that, since this data is time sensitive. Future prices may imply past prices. When I edited your code to reflect this change (divide the first 70% of the data as training set and last 30% as test set), the accuracy drops down to 50%, unfortunately. I wish it didnt :)
> 
> Best,
> Cem

can you please share you changes for how you modified it to change the data slpitting please

**Comment by diskmail34** [comment]
> Merhaba,
> 
> Kodunuzu kontrol ettim ve eğitim ve test verilerini bölme oranına göre rastgele böldüğünü fark ettim. Ancak borsalar söz konusu olduğunda, bu veriler zamana duyarlı olduğu için bunu yapabileceğinizi düşünmüyorum. Gelecekteki fiyatlar, geçmiş fiyatları ifade edebilir. Kodunuzu bu değişikliği yansıtacak şekilde düzenlediğimde (verinin ilk %70'ini eğitim seti ve son %30'unu test seti olarak bölün), doğruluk maalesef %50'ye düşüyor. keşke olmasaydı :)
> 
> En iyi, Cem

Merhaba,

Durum ile ilgili yardımınza, fikirinize ihtiyacım var. Yüksek lisans öğrencisiyim.
Hocamız konuyu işlemeden proje verdi. Maalsef yazılım konusunda neredeyse sıfıt bilgiye sahibim.

JupyterLab,, Python 3.10 (64-bit) programlarını kurdum fakat çalıştıramadım.
Hocamız bizden sunum ve proje şeklinde istiyor. İçerisinde K-Means,  Naive Bayes, Cart işlemleri barındıracak.

Ben bu kütüphaneyi kullandım fakat çalıştıramıyorum.
![1](https://user-images.githubusercontent.com/104549674/165918662-d2ae27b6-9f82-471b-8f23-393626b2f942.jpg)

Yardımlarınızı, fikirlerinizi ivedi ile bekleyeceğim.
Teşekkürler.
